# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2022-Today Datadog, Inc.

# SETUP

variables:
  REPO: 'dd-sdk-roku'
  CI_IMAGE_VERSION: "7"
  CI_IMAGE: 'registry.ddbuild.io/ci/$REPO:$CI_IMAGE_VERSION'
  GIT_REPOSITORY: 'git@github.com:DataDog/dd-sdk-roku.git'
  MAIN_BRANCH: 'main'
  GIT_DEPTH: 5

  DD_AGENT_HOST: "$BUILDENV_HOST_IP"
  DD_SERVICE: "dd-sdk-roku"
  DD_ENV_TESTS: "ci"
  DD_INTEGRATION_JUNIT_5_ENABLED: "true"
  DD_CIVISIBILITY_ENABLED: "true"
  DD_INSIDE_CI: "true"

stages:
  - ci-image
  - analysis
  - test

.base-configuration:
  tags: ['arch:amd64']
  image: $CI_IMAGE

.node-configuration:
  extends:
    - .base-configuration
  before_script:
    - npm ci

########################################################################################################################
# CI IMAGE
########################################################################################################################

ci-image:
  stage: ci-image
  when: manual
  except: [ tags, schedules ]
  tags: ['arch:amd64']
  image: "registry.ddbuild.io/images/docker:27.3.1"
  id_tokens:
    DDSIGN_ID_TOKEN:
      aud: image-integrity
  script:
    - echo $CI_IMAGE
    - METADATA_FILE=$(mktemp)
    - docker buildx build
      --file Dockerfile.gitlab
      --platform linux/amd64
      --tag $CI_IMAGE
      --push
      --metadata-file ${METADATA_FILE}
      .
    - ddsign sign $CI_IMAGE --docker-metadata-file ${METADATA_FILE}

########################################################################################################################
# STATIC ANALYSIS
########################################################################################################################

analysis:check_copyright:
  extends:
    - .base-configuration
  stage: analysis
  timeout: 30m
  script:
    - tools/copyright/check_copyright.sh

analysis:lint:
  extends:
    - .node-configuration
  stage: analysis
  timeout: 30m
  script:
    - npm run lint

analysis:sca-test:
  extends:
    - .node-configuration
  stage: analysis
  timeout: 30m
  script:
    - export ROKU_SCA="/usr/bin/roku-sca/bin/sca-cmd"
    - npm run sca-test

analysis:sca-sample:
  extends:
    - .node-configuration
  stage: analysis
  timeout: 30m
  script:
    - export ROKU_SCA="/usr/bin/roku-sca/bin/sca-cmd"
    - npm run sca-sample

analysis:check-dist:
  extends:
    - .node-configuration
  stage: analysis
  timeout: 30m
  script:
    - npm run check-dist

########################################################################################################################
# TESTS
########################################################################################################################

test:roku:
# disabled for now as we need a device in CI to run the tests :/
  when: manual
  extends:
    - .node-configuration
  stage: test
  timeout: 1h
  script:
    - npm test
