FROM node:24.16.0-bookworm-slim AS node

FROM registry.ddbuild.io/images/mirror/ubuntu:24.04

####################################################################################################
# DEBIAN SETUP
####################################################################################################

ENV DEBIAN_FRONTEND=noninteractive

# Set timezone to UTC by default
RUN ln -sf /usr/share/zoneinfo/Etc/UTC /etc/localtime

# Make sure APT is up to date
RUN apt-get update
RUN apt-get -y upgrade
RUN set -x && apt-get -y install --no-install-recommends apt-utils

# Install CLI tools
RUN set -x && apt-get -y install --no-install-recommends \
   curl \
   ca-certificates \
   git \
   make \
   unzip \
   zip \
   && apt-get -y clean\
   && rm -rf /var/lib/apt/lists/*

####################################################################################################
# PYTHON
####################################################################################################

# Install Python 3
RUN set -x \
   && apt-get update \
   && apt-get -y upgrade \
   && apt-get -y install --no-install-recommends \
   python3 \
   python3-apt \
   python3-pip \
   pipx \
   && apt-get -y clean \
   && rm -rf /var/lib/apt/lists/*

#  Install pip for aws
# RUN set -x \
#    && curl -OL https://bootstrap.pypa.io/get-pip.py \
#    && python3 get-pip.py \
#    && rm get-pip.py

RUN python3 --version

#  Install aws CLI
RUN set -x && pipx install awscli

####################################################################################################
# JAVA
####################################################################################################

RUN set -x \
   && apt-get update \
   && apt-get -y upgrade \
   && apt-get -y install --no-install-recommends \
   openjdk-21-jdk \
   && apt-get -y clean \
   && rm -rf /var/lib/apt/lists/*
RUN java --version

####################################################################################################
# NPM
####################################################################################################

# Install Node
COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm

RUN npm install -g npm@11.16.0

# Check Node and NPM version
RUN node --version
RUN npm --version

####################################################################################################
# ROKU
####################################################################################################

ENV ROKU_SCA_URL="https://devtools.web.roku.com/static-channel-analysis/sca-cmd.zip"
ENV ROKU_SCA_SHA256="fc0b5de203e135463d0510994ace222320549dc5f22ec8f456e6b63b81c20d64"
RUN curl -L $ROKU_SCA_URL -o sca-cmd.zip \
   && echo "${ROKU_SCA_SHA256} sca-cmd.zip" | sha256sum -c  \
   && unzip sca-cmd.zip \
   && mv sca-cmd /usr/bin/roku-sca \
   && rm -Rf sca-cmd sca-cmd.zip

####################################################################################################
# EOF
####################################################################################################
