' Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
' This product includes software developed at Datadog (https://www.datadoghq.com/).
' Copyright 2022-Today Datadog, Inc.

'----------------------------------------------------------------
' Main setup function.
' @return A configured TestSuite object.
'----------------------------------------------------------------
function TestSuite__DdUrlTransfer() as object
    this = BaseTestSuite()
    this.Name = "DdUrlTransfer"

    this.addTest("WhenGetTracedHeaderType_ThenReturnsHeaderType", DdUrlTransferTest__WhenGetTracedHeaderType_ThenReturnsHeaderType)
    this.addTest("WhenGetTracedHeaderTypeWithSingleHost_ThenReturnsHeaderType", DdUrlTransferTest__WhenGetTracedHeaderTypeWithSingleHost_ThenReturnsHeaderType)
    this.addTest("WhenGetTracedHeaderTypeWithUnknownHost_ThenReturnsInvalid", DdUrlTransferTest__WhenGetTracedHeaderTypeWithUnknownHost_ThenReturnsInvalid)
    this.addTest("WhenGetTracedHeaderTypeWithNoHost_ThenReturnsInvalid", DdUrlTransferTest__WhenGetTracedHeaderTypeWithNoHost_ThenReturnsInvalid)
    this.addTest("WhenGetTracedHeaderTypeWithNonUrl_ThenReturnsInvalid", DdUrlTransferTest__WhenGetTracedHeaderTypeWithNonUrl_ThenReturnsInvalid)

    this.addTest("WhenPadLeftWithEmptyString_ThenReturnPaddedString", DdUrlTransferTest__WhenPadLeftWithEmptyString_ThenReturnPaddedString)
    this.addTest("WhenPadLeftWithExactSizeString_ThenReturnOriginalString", DdUrlTransferTest__WhenPadLeftWithExactSizeString_ThenReturnOriginalString)
    this.addTest("WhenPadLeftWithLargeString_ThenReturnOriginalString", DdUrlTransferTest__WhenPadLeftWithLargeString_ThenReturnOriginalString)
    this.addTest("WhenPadLeftWithSmallString_ThenReturnOriginalString", DdUrlTransferTest__WhenPadLeftWithSmallString_ThenReturnOriginalString)

    this.addTest("WhenGenerateUniqueId64_ThenGenerateIdDecimal", DdUrlTransferTest__WhenGenerateUniqueId64_ThenGenerateIdDecimal)
    this.addTest("WhenGenerateUniqueId64_ThenGenerateIdHexadecimal", DdUrlTransferTest__WhenGenerateUniqueId64_ThenGenerateIdHexadecimal)
    this.addTest("WhenGenerateUniqueId128_ThenGenerateIdDecimal", DdUrlTransferTest__WhenGenerateUniqueId128_ThenGenerateIdDecimal)
    this.addTest("WhenGenerateUniqueId128_ThenGenerateIdHexadecimal", DdUrlTransferTest__WhenGenerateUniqueId128_ThenGenerateIdHexadecimal)
    this.addTest("WhenGenerateUniqueIdDd_ThenGenerateAllId", DdUrlTransferTest__WhenGenerateUniqueIdDd_ThenGenerateAllId)
    this.addTest("WhenPrintIdToString_ThenGenerateStringId", DdUrlTransferTest__WhenPrintIdToString_ThenGenerateStringId)
    this.addTest("WhenAddSampledInHeaders_ThenHeadersHaveSessionId", DdUrlTransferTest__WhenAddSampledInHeaders_ThenHeadersHaveSessionId)
    this.addTest("WhenDeleteTracingHeaders_ThenDeleteOnlySessionId", DdUrlTransferTest__WhenDeleteTracingHeaders_ThenDeleteOnlySessionId)
    this.addTest("WhenDeleteTracingHeaders_ThenDeleteCorrectHeaders", DdUrlTransferTest__WhenDeleteTracingHeaders_ThenDeleteCorrectHeaders)

    this.addTest("WhenSampledIn_ThenHaveSampleInHeaders", DdUrlTransferTest__WhenSampledIn_ThenHaveSampleInHeaders)
    this.addTest("WhenSampledOutAndTraceContextInjectionAll_ThenHaveSampleInHeaders", DdUrlTransferTest__WhenSampledOutAndTraceContextInjectionAll_ThenHaveSampleInHeaders)
    this.addTest("WhenSampledOutAndTraceContextInjectioSampled_ThenHaveSampleInHeaders", DdUrlTransferTest__WhenSampledOutAndTraceContextInjectioSampled_ThenHaveSampleInHeaders)
    return this
end function

'----------------------------------------------------------------
' Given:
'  When: call getTracedHeaderType with a url with host in the validhost list
'  Then: returns the header type
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGetTracedHeaderType_ThenReturnsHeaderType() as string
    ' Given
    validHosts = []
    for i = 0 to 10
        host = IG_GetString(12) + "." + IG_GetString(3)
        validHosts.Push({ host: host, header: IG_GetOneOf(["b3", "datadog", "b3multi", "tracecontext"]) })
    end for
    validHost = validHosts[IG_GetIntegerInRange(0, 10)]
    url = "https://" + validHost.host + "/" + IG_GetString(16)

    ' When
    result = datadogroku_getTracedHeaderType(url, validHosts)

    ' Then
    Assert.that(result).isEqualTo(validHost.header)
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call getTracedHeaderType with a url with host in the validhost list
'  Then: returns the header type
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGetTracedHeaderTypeWithSingleHost_ThenReturnsHeaderType() as string
    ' Given
    validHost = IG_GetString(12) + "." + IG_GetString(3)
    headerType = IG_GetOneOf(["b3", "datadog", "b3multi", "tracecontext"])
    validHosts = []
    validHosts.Push({ host: validHost, header: headerType })
    url = "https://" + validHost + "/" + IG_GetString(16)

    ' When
    result = datadogroku_getTracedHeaderType(url, validHosts)

    ' Then
    Assert.that(result).isEqualTo(headerType)
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call getTracedHeaderType with a url with host not in the validhost list
'  Then: returns invalid
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGetTracedHeaderTypeWithUnknownHost_ThenReturnsInvalid() as string
    ' Given
    validHosts = []
    for i = 0 to 10
        validHosts.Push({ host: IG_GetString(12) + "." + IG_GetString(3), header: IG_GetOneOf(["b3", "datadog", "b3multi", "tracecontext"]) })
    end for
    url = "https://" + IG_GetString(8) + "." + IG_GetString(2) + "/" + IG_GetString(16)

    ' When
    result = datadogroku_getTracedHeaderType(url, validHosts)

    ' Then
    Assert.that(result).isInvalid()
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call getTracedHeaderType with a url with host not in the validhost list (empty)
'  Then: returns invalid
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGetTracedHeaderTypeWithNoHost_ThenReturnsInvalid() as string
    ' Given
    validHosts = []
    url = "https://" + IG_GetString(8) + "." + IG_GetString(2) + "/" + IG_GetString(16)

    ' When
    result = datadogroku_getTracedHeaderType(url, validHosts)

    ' Then
    Assert.that(result).isInvalid()
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call getTracedHeaderType with a string not a url
'  Then: returns invalid
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGetTracedHeaderTypeWithNonUrl_ThenReturnsInvalid() as string
    ' Given
    validHosts = []
    for i = 0 to 10
        validHosts.Push({ host: IG_GetString(12) + "." + IG_GetString(3), header: IG_GetOneOf(["b3", "datadog", "b3multi", "tracecontext"]) })
    end for
    url = IG_GetString(64)

    ' When
    result = datadogroku_getTracedHeaderType(url, validHosts)

    ' Then
    Assert.that(result).isInvalid()
    return ""
end function


'----------------------------------------------------------------
' Given: an empty string and a padding string
'  When: call padLeft
'  Then: returns padded string
'----------------------------------------------------------------
function DdUrlTransferTest__WhenPadLeftWithEmptyString_ThenReturnPaddedString() as string
    ' Given
    length = IG_GetIntegerInRange(10, 20)
    pad = IG_GetString(1)

    ' When
    result = datadogroku_padLeft("", length, pad)

    ' Then
    Assert.that(result).hasSize(length).hasSubstring(pad + pad + pad + pad + pad + pad + pad + pad + pad)
    return ""
end function

'----------------------------------------------------------------
' Given: a size N, and a string of size N
'  When: call padLeft
'  Then: returns the original string string
'----------------------------------------------------------------
function DdUrlTransferTest__WhenPadLeftWithExactSizeString_ThenReturnOriginalString() as string
    ' Given
    input = IG_GetString(20)
    length = input.Len()
    pad = IG_GetString(1)

    ' When
    result = datadogroku_padLeft(input, length, pad)

    ' Then
    Assert.that(result).isEqualTo(input)
    return ""
end function

'----------------------------------------------------------------
' Given: a size N, and a string of size > N
'  When: call padLeft
'  Then: returns the original string string
'----------------------------------------------------------------
function DdUrlTransferTest__WhenPadLeftWithLargeString_ThenReturnOriginalString() as string
    ' Given
    input = IG_GetString(10) + IG_GetString(10) + IG_GetString(10) + IG_GetString(10)
    length = input.Len() / 2
    pad = IG_GetString(1)

    ' When
    result = datadogroku_padLeft(input, length, pad)

    ' Then
    Assert.that(result).isEqualTo(input)
    return ""
end function

'----------------------------------------------------------------
' Given: a size N, and a string of size < N
'  When: call padLeft
'  Then: returns the original string string
'----------------------------------------------------------------
function DdUrlTransferTest__WhenPadLeftWithSmallString_ThenReturnOriginalString() as string
    ' Given
    length = IG_GetIntegerInRange(10, 20)
    pad = IG_GetString(1)
    input = IG_GetString(IG_GetIntegerInRange(1, length - 1))

    ' When
    result = datadogroku_padLeft(input, length, pad)

    ' Then
    Assert.that(result).hasSize(length).hasSubstring(pad + input)
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call the generateUniqueId64 method
'  Then: returns a 64 bits unique id
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGenerateUniqueId64_ThenGenerateIdDecimal() as string
    ' Given

    ' When
    id = datadogroku_generateUniqueId64()

    ' Then
    ' 64 bit ids will never have more than 20 chars in decimal representation
    Assert.that(Len(id)).isInRange(1, 20)
    Assert.that(id).matches("^[0-9]+$")
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call the generateUniqueId64 method
'  Then: returns a 64 bits unique id
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGenerateUniqueId64_ThenGenerateIdHexadecimal() as string
    ' Given

    ' When
    id = datadogroku_generateUniqueId64(16)

    ' Then
    ' 64 bit ids will never have more than 16 chars in hexadecimal representation
    Assert.that(Len(id)).isInRange(1, 16)
    Assert.that(id).matches("^[0-9a-f]+$", "i")
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call the generateUniqueId64 method
'  Then: returns a 64 bits unique id
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGenerateUniqueId128_ThenGenerateIdDecimal() as string
    ' Given

    ' When
    id = datadogroku_generateUniqueId128()

    ' Then
    ' 64 bit ids will never have more than 39 chars in decimal representation
    Assert.that(Len(id)).isInRange(1, 39)
    Assert.that(id).matches("^[0-9]+$")
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call the generateUniqueId64 method
'  Then: returns a 64 bits unique id
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGenerateUniqueId128_ThenGenerateIdHexadecimal() as string
    ' Given

    ' When
    id = datadogroku_generateUniqueId128(16)

    ' Then
    ' 64 bit ids will never have more than 32 chars in hexadecimal representation
    Assert.that(Len(id)).isInRange(1, 32)
    Assert.that(id).matches("^[0-9a-f]+$", "i")
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call the printIdToString method
'  Then: returns a 64 bits unique id
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGenerateUniqueIdDd_ThenGenerateAllId() as string
    ' Given

    ' When
    id = datadogroku_generateUniqueIdDd()

    ' Then
    Assert.that(id).hasSize(3)
    ' the full id always starts with the high id as both are hexadecimal representations
    Assert.that(id[0]).matches("^" + id[2] + "[0-9a-f]{16}$", "i")
    Assert.that(id[1]).matches("^[0-9]+$", "i")
    Assert.that(id[2]).matches("^[0-9a-f]+$", "i")
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call the printIdToString method
'  Then: returns a 64 bits unique id
'----------------------------------------------------------------
function DdUrlTransferTest__WhenPrintIdToString_ThenGenerateStringId() as string
    ' some special cases / Decimal
    decRadix = 10
    Assert.that(datadogroku_printIdToString(0, 0, 0, 42, decRadix)).isEqualTo("42")
    Assert.that(datadogroku_printIdToString(0, 0, 16, 0, decRadix)).isEqualTo("68719476736")
    Assert.that(datadogroku_printIdToString(0, 815, 0, 0, decRadix)).isEqualTo("15034096420073284567040")
    Assert.that(datadogroku_printIdToString(23, 0, 13, 0, decRadix)).isEqualTo("1822247737828079764707345432576")

    ' some special cases / Hexadecimal
    hexRadix = 16
    Assert.that(datadogroku_printIdToString(0, 0, 0, 42, hexRadix)).isEqualTo("2a")
    Assert.that(datadogroku_printIdToString(0, 0, 16, 0, hexRadix)).isEqualTo("1000000000")
    Assert.that(datadogroku_printIdToString(0, 815, 0, 0, hexRadix)).isEqualTo("32f0000000000000000")
    Assert.that(datadogroku_printIdToString(23, 0, 0, 0, hexRadix)).isEqualTo("17000000000000000000000000")

    return ""
end function

function DdUrlTransferTest__WhenAddSampledInHeaders_ThenHeadersHaveSessionId() as string

    fakeSessionId = IG_GetString(32)
    fakeGlobal = createFakeGlobal(fakeSessionId)
    fakeHeaderType = IG_GetOneOf(["b3", "datadog", "b3multi", "tracecontext"])
    ddUrlTransfer = datadogroku_DdUrlTransfer(fakeGlobal)
    ddUrlTransfer._addSampledInHeaders(fakeHeaderType)
    resultList = ddUrlTransfer.GetHeader("baggage")
    Assert.that(resultList).hasSize(1)
    Assert.that(resultList[0]).isEqualTo("session.id="+fakeSessionId)
    return ""
end function


function DdUrlTransferTest__WhenDeleteTracingHeaders_ThenDeleteOnlySessionId() as string
    
    fakeSessionId = IG_GetString(32)
    fake3rdBaggage = IG_GetString(32)
    fakeGlobal = createFakeGlobal(fakeSessionId)
    ddUrlTransfer = datadogroku_DdUrlTransfer(fakeGlobal)
    ddUrlTransfer.addHeader("baggage", "session.id=" + fakeSessionId)
    ddUrlTransfer.addHeader("baggage", fake3rdBaggage)

    ddUrlTransfer._deleteTracingHeaders()

    resultList = ddUrlTransfer.GetHeader("baggage")
    Assert.that(resultList).hasSize(1)
    Assert.that(resultList[0]).isEqualTo(fake3rdBaggage)
    return ""

end function

function DdUrlTransferTest__WhenDeleteTracingHeaders_ThenDeleteCorrectHeaders() as string

    fakeSessionId = IG_GetString(32)
    fakeDatadogTraceId = IG_GetString(32)
    fakeDatadogParentId = IG_GetString(32)
    fakeDatadogSamplingPriority = IG_GetString(32)
    fakeDatadogOrigin = IG_GetString(32)
    fakeB3 = IG_GetString(32)
    fakeB3TraceId = IG_GetString(32)
    fakeB3SpanId = IG_GetString(32)
    fakeB3Sampled = IG_GetString(32)
    fakeTraceParent = IG_GetString(32)
    fakeTraceState = IG_GetString(32)

    fakeGlobal = createFakeGlobal(fakeSessionId)
    ddUrlTransfer = datadogroku_DdUrlTransfer(fakeGlobal)
    ddUrlTransfer.addHeader("x-datadog-trace-id", fakeDatadogTraceId)
    ddUrlTransfer.addHeader("x-datadog-parent-id", fakeDatadogParentId)
    ddUrlTransfer.addHeader("x-datadog-sampling-priority", fakeDatadogSamplingPriority)
    ddUrlTransfer.addHeader("x-datadog-origin", fakeDatadogOrigin)
    ddUrlTransfer.addHeader("b3", fakeB3)
    ddUrlTransfer.addHeader("X-B3-TraceId", fakeB3TraceId)
    ddUrlTransfer.addHeader("X-B3-SpanId", fakeB3SpanId)
    ddUrlTransfer.addHeader("X-B3-Sampled", fakeB3Sampled)
    ddUrlTransfer.addHeader("traceparent", fakeTraceParent)
    ddUrlTransfer.addHeader("tracestate", fakeTraceState)

    ddUrlTransfer._deleteTracingHeaders()

    resultDatadogTraceId = ddUrlTransfer.GetHeader("x-datadog-trace-id")
    resultDatadogParentId = ddUrlTransfer.GetHeader("x-datadog-parent-id")
    resultDatadogSamplingPriority = ddUrlTransfer.GetHeader("x-datadog-sampling-priority")
    resultDatadogOrigin = ddUrlTransfer.GetHeader("x-datadog-origin")
    resultB3 = ddUrlTransfer.GetHeader("b3")
    resultB3TraceId = ddUrlTransfer.GetHeader("X-B3-TraceId")
    resultB3SpanId = ddUrlTransfer.GetHeader("X-B3-SpanId")
    resultB3Sampled= ddUrlTransfer.GetHeader("X-B3-Sampled")
    resultTraceParent = ddUrlTransfer.GetHeader("traceparent")
    resultTraceState = ddUrlTransfer.GetHeader("tracestate")
    Assert.that(resultDatadogTraceId).hasSize(0)
    Assert.that(resultDatadogParentId).hasSize(0)
    Assert.that(resultDatadogSamplingPriority).hasSize(0)
    Assert.that(resultDatadogOrigin).hasSize(0)
    Assert.that(resultB3).hasSize(0)
    Assert.that(resultB3TraceId).hasSize(0)
    Assert.that(resultB3SpanId).hasSize(0)
    Assert.that(resultB3Sampled).hasSize(0)
    Assert.that(resultTraceParent).hasSize(0)
    Assert.that(resultTraceState).hasSize(0)
    return ""

end function

function DdUrlTransferTest__WhenSampledIn_ThenHaveSampleInHeaders() as string
    fakeSessionId = IG_GetString(16)
    fakeDatadogRumAgent = CreateObject("roSGNode", "datadogRoku_RumAgent") 
    fakeId = IG_GetInteger()
    fakeName = IG_GetString(16)
    fakeEmail = IG_GetString(32)
    fakeGlobal = {
        datadogRumContext: {
            sessionId: fakeSessionId
        },
        datadogRumAgent: fakeDatadogRumAgent,
        datadogTraceAgent: {
            traceSampleRate: 100,
            tracingHeaderTypes: [
                {
                    "host": "datadog.com",
                    "header": "datadog"
                }
            ],
            traceContextInjection: "sampled"
        },
        datadogUserInfo:  { id: fakeId, name: fakeName, email: fakeEmail}
    }
    ddUrlTransfer = datadogroku_DdUrlTransfer(fakeGlobal)
    ddUrlTransfer.SetUrl("https://datadog.com")
    ddUrlTransfer.SetTraceSampleRate(100)
    ddUrlTransfer._traceRequest()
    result = ddUrlTransfer.GetHeader("baggage")
    Assert.that(result[0]).isEqualTo("session.id=" + fakeSessionId)
    return ""
end function


function DdUrlTransferTest__WhenSampledOutAndTraceContextInjectionAll_ThenHaveSampleInHeaders() as string
    fakeSessionId = IG_GetString(16)
    fakeDatadogRumAgent = CreateObject("roSGNode", "datadogRoku_RumAgent") 
    fakeId = IG_GetInteger()
    fakeName = IG_GetString(16)
    fakeEmail = IG_GetString(32)
    fakeGlobal = {
        datadogRumContext: {
            sessionId: fakeSessionId
        },
        datadogRumAgent: fakeDatadogRumAgent,
        datadogTraceAgent: {
            traceSampleRate: 0,
            tracingHeaderTypes: [
                {
                    "host": "datadog.com",
                    "header": "datadog"
                }
            ],
            traceContextInjection: "all"
        },
        datadogUserInfo:  { id: fakeId, name: fakeName, email: fakeEmail}
    }
    ddUrlTransfer = datadogroku_DdUrlTransfer(fakeGlobal)
    ddUrlTransfer.SetUrl("https://datadog.com")
    ddUrlTransfer._traceRequest()
    result = ddUrlTransfer.GetHeader("x-datadog-sampling-priority")
    Assert.that(result[0]).isEqualTo("0")
    return ""
end function

function DdUrlTransferTest__WhenSampledOutAndTraceContextInjectioSampled_ThenHaveSampleInHeaders() as string
    fakeSessionId = IG_GetString(16)
    fakeDatadogRumAgent = CreateObject("roSGNode", "datadogRoku_RumAgent") 
    fakeId = IG_GetInteger()
    fakeName = IG_GetString(16)
    fakeEmail = IG_GetString(32)
    fakeGlobal = {
        datadogRumContext: {
            sessionId: fakeSessionId
        },
        datadogRumAgent: fakeDatadogRumAgent,
        datadogTraceAgent: {
            traceSampleRate: 0,
            tracingHeaderTypes: [
                {
                    "host": "datadog.com",
                    "header": "datadog"
                }
            ],
            traceContextInjection: "sampled"
        },
        datadogUserInfo:  { id: fakeId, name: fakeName, email: fakeEmail}
    }
    ddUrlTransfer = datadogroku_DdUrlTransfer(fakeGlobal)
    ddUrlTransfer.SetUrl("https://datadog.com")
    ddUrlTransfer._traceRequest()
    result = ddUrlTransfer.GetHeader("x-datadog-sampling-priority")
    Assert.that(result).hasSize(0)
    return ""
end function

function createFakeGlobal(fakeSessionId as string) as object
    fakeDatadogRumAgent = CreateObject("roSGNode", "datadogRoku_RumAgent") 
    fakeSampleRate = IG_GetDouble()
    fakeId = IG_GetString(8)
    fakeName = IG_GetString(16)
    fakeEmail = IG_GetString(32)
    fakeGlobal = {
        datadogRumContext: {
            sessionId: fakeSessionId
        },
        datadogRumAgent: fakeDatadogRumAgent,
        datadogTraceAgent: {
            traceSampleRate: fakeSampleRate,
            tracingHeaderTypes: ["X-Trace-ID", "X-Request-ID"]
        },
        datadogUserInfo:  { id: fakeId, name: fakeName, email: fakeEmail}
    }
    return fakeGlobal

end function

