' Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
' This product includes software developed at Datadog (https://www.datadoghq.com/).
' Copyright 2022-Today Datadog, Inc.

'----------------------------------------------------------------
' Main setup function.
' @return A configured TestSuite object.
'----------------------------------------------------------------
function TestSuite__DdUrlTransfer() as object
    this = BaseTestSuite()
    this.Name = "DdUrlTransfer"

    this.addTest("WhenGetTracedHeaderType_ThenReturnsHeaderType", DdUrlTransferTest__WhenGetTracedHeaderType_ThenReturnsHeaderType)
    this.addTest("WhenGetTracedHeaderTypeWithSingleHost_ThenReturnsHeaderType", DdUrlTransferTest__WhenGetTracedHeaderTypeWithSingleHost_ThenReturnsHeaderType)
    this.addTest("WhenGetTracedHeaderTypeWithUnknownHost_ThenReturnsInvalid", DdUrlTransferTest__WhenGetTracedHeaderTypeWithUnknownHost_ThenReturnsInvalid)
    this.addTest("WhenGetTracedHeaderTypeWithNoHost_ThenReturnsInvalid", DdUrlTransferTest__WhenGetTracedHeaderTypeWithNoHost_ThenReturnsInvalid)
    this.addTest("WhenGetTracedHeaderTypeWithNonUrl_ThenReturnsInvalid", DdUrlTransferTest__WhenGetTracedHeaderTypeWithNonUrl_ThenReturnsInvalid)

    this.addTest("WhenPadLeftWithEmptyString_ThenReturnPaddedString", DdUrlTransferTest__WhenPadLeftWithEmptyString_ThenReturnPaddedString)
    this.addTest("WhenPadLeftWithExactSizeString_ThenReturnOriginalString", DdUrlTransferTest__WhenPadLeftWithExactSizeString_ThenReturnOriginalString)
    this.addTest("WhenPadLeftWithLargeString_ThenReturnOriginalString", DdUrlTransferTest__WhenPadLeftWithLargeString_ThenReturnOriginalString)
    this.addTest("WhenPadLeftWithSmallString_ThenReturnOriginalString", DdUrlTransferTest__WhenPadLeftWithSmallString_ThenReturnOriginalString)

    this.addTest("WhenGenerateUniqueId64_ThenGenerateIdDecimal", DdUrlTransferTest__WhenGenerateUniqueId64_ThenGenerateIdDecimal)
    this.addTest("WhenGenerateUniqueId64_ThenGenerateIdHexadecimal", DdUrlTransferTest__WhenGenerateUniqueId64_ThenGenerateIdHexadecimal)
    this.addTest("WhenGenerateUniqueId128_ThenGenerateIdDecimal", DdUrlTransferTest__WhenGenerateUniqueId128_ThenGenerateIdDecimal)
    this.addTest("WhenGenerateUniqueId128_ThenGenerateIdHexadecimal", DdUrlTransferTest__WhenGenerateUniqueId128_ThenGenerateIdHexadecimal)
    this.addTest("WhenGenerateUniqueIdDd_ThenGenerateAllId", DdUrlTransferTest__WhenGenerateUniqueIdDd_ThenGenerateAllId)
    this.addTest("WhenPrintIdToString_ThenGenerateStringId", DdUrlTransferTest__WhenPrintIdToString_ThenGenerateStringId)

    return this
end function

'----------------------------------------------------------------
' Given:
'  When: call getTracedHeaderType with a url with host in the validhost list
'  Then: returns the header type
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGetTracedHeaderType_ThenReturnsHeaderType() as string
    ' Given
    validHosts = []
    for i = 0 to 10
        host = IG_GetString(12) + "." + IG_GetString(3)
        validHosts.Push({ host: host, header: IG_GetOneOf(["b3", "datadog", "b3multi", "tracecontext"]) })
    end for
    validHost = validHosts[IG_GetIntegerInRange(0, 10)]
    url = "https://" + validHost.host + "/" + IG_GetString(16)

    ' When
    result = datadogroku_getTracedHeaderType(url, validHosts)

    ' Then
    Assert.that(result).isEqualTo(validHost.header)
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call getTracedHeaderType with a url with host in the validhost list
'  Then: returns the header type
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGetTracedHeaderTypeWithSingleHost_ThenReturnsHeaderType() as string
    ' Given
    validHost = IG_GetString(12) + "." + IG_GetString(3)
    headerType = IG_GetOneOf(["b3", "datadog", "b3multi", "tracecontext"])
    validHosts = []
    validHosts.Push({ host: validHost, header: headerType })
    url = "https://" + validHost + "/" + IG_GetString(16)

    ' When
    result = datadogroku_getTracedHeaderType(url, validHosts)

    ' Then
    Assert.that(result).isEqualTo(headerType)
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call getTracedHeaderType with a url with host not in the validhost list
'  Then: returns invalid
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGetTracedHeaderTypeWithUnknownHost_ThenReturnsInvalid() as string
    ' Given
    validHosts = []
    for i = 0 to 10
        validHosts.Push({ host: IG_GetString(12) + "." + IG_GetString(3), header: IG_GetOneOf(["b3", "datadog", "b3multi", "tracecontext"]) })
    end for
    url = "https://" + IG_GetString(8) + "." + IG_GetString(2) + "/" + IG_GetString(16)

    ' When
    result = datadogroku_getTracedHeaderType(url, validHosts)

    ' Then
    Assert.that(result).isInvalid()
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call getTracedHeaderType with a url with host not in the validhost list (empty)
'  Then: returns invalid
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGetTracedHeaderTypeWithNoHost_ThenReturnsInvalid() as string
    ' Given
    validHosts = []
    url = "https://" + IG_GetString(8) + "." + IG_GetString(2) + "/" + IG_GetString(16)

    ' When
    result = datadogroku_getTracedHeaderType(url, validHosts)

    ' Then
    Assert.that(result).isInvalid()
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call getTracedHeaderType with a string not a url
'  Then: returns invalid
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGetTracedHeaderTypeWithNonUrl_ThenReturnsInvalid() as string
    ' Given
    validHosts = []
    for i = 0 to 10
        validHosts.Push({ host: IG_GetString(12) + "." + IG_GetString(3), header: IG_GetOneOf(["b3", "datadog", "b3multi", "tracecontext"]) })
    end for
    url = IG_GetString(64)

    ' When
    result = datadogroku_getTracedHeaderType(url, validHosts)

    ' Then
    Assert.that(result).isInvalid()
    return ""
end function


'----------------------------------------------------------------
' Given: an empty string and a padding string
'  When: call padLeft
'  Then: returns padded string
'----------------------------------------------------------------
function DdUrlTransferTest__WhenPadLeftWithEmptyString_ThenReturnPaddedString() as string
    ' Given
    length = IG_GetIntegerInRange(10, 20)
    pad = IG_GetString(1)

    ' When
    result = datadogroku_padLeft("", length, pad)

    ' Then
    Assert.that(result).hasSize(length).hasSubstring(pad + pad + pad + pad + pad + pad + pad + pad + pad)
    return ""
end function

'----------------------------------------------------------------
' Given: a size N, and a string of size N
'  When: call padLeft
'  Then: returns the original string string
'----------------------------------------------------------------
function DdUrlTransferTest__WhenPadLeftWithExactSizeString_ThenReturnOriginalString() as string
    ' Given
    input = IG_GetString(20)
    length = input.Len()
    pad = IG_GetString(1)

    ' When
    result = datadogroku_padLeft(input, length, pad)

    ' Then
    Assert.that(result).isEqualTo(input)
    return ""
end function

'----------------------------------------------------------------
' Given: a size N, and a string of size > N
'  When: call padLeft
'  Then: returns the original string string
'----------------------------------------------------------------
function DdUrlTransferTest__WhenPadLeftWithLargeString_ThenReturnOriginalString() as string
    ' Given
    input = IG_GetString(10) + IG_GetString(10) + IG_GetString(10) + IG_GetString(10)
    length = input.Len() / 2
    pad = IG_GetString(1)

    ' When
    result = datadogroku_padLeft(input, length, pad)

    ' Then
    Assert.that(result).isEqualTo(input)
    return ""
end function

'----------------------------------------------------------------
' Given: a size N, and a string of size < N
'  When: call padLeft
'  Then: returns the original string string
'----------------------------------------------------------------
function DdUrlTransferTest__WhenPadLeftWithSmallString_ThenReturnOriginalString() as string
    ' Given
    length = IG_GetIntegerInRange(10, 20)
    pad = IG_GetString(1)
    input = IG_GetString(IG_GetIntegerInRange(1, length - 1))

    ' When
    result = datadogroku_padLeft(input, length, pad)

    ' Then
    Assert.that(result).hasSize(length).hasSubstring(pad + input)
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call the generateUniqueId64 method
'  Then: returns a 64 bits unique id
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGenerateUniqueId64_ThenGenerateIdDecimal() as string
    ' Given

    ' When
    id = datadogroku_generateUniqueId64()

    ' Then
    ' 64 bit ids will never have more than 20 chars in decimal representation
    Assert.that(Len(id)).isInRange(1, 20)
    Assert.that(id).matches("^[0-9]+$")
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call the generateUniqueId64 method
'  Then: returns a 64 bits unique id
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGenerateUniqueId64_ThenGenerateIdHexadecimal() as string
    ' Given

    ' When
    id = datadogroku_generateUniqueId64(16)

    ' Then
    ' 64 bit ids will never have more than 16 chars in hexadecimal representation
    Assert.that(Len(id)).isInRange(1, 16)
    Assert.that(id).matches("^[0-9a-f]+$", "i")
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call the generateUniqueId64 method
'  Then: returns a 64 bits unique id
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGenerateUniqueId128_ThenGenerateIdDecimal() as string
    ' Given

    ' When
    id = datadogroku_generateUniqueId128()

    ' Then
    ' 64 bit ids will never have more than 39 chars in decimal representation
    Assert.that(Len(id)).isInRange(1, 39)
    Assert.that(id).matches("^[0-9]+$")
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call the generateUniqueId64 method
'  Then: returns a 64 bits unique id
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGenerateUniqueId128_ThenGenerateIdHexadecimal() as string
    ' Given

    ' When
    id = datadogroku_generateUniqueId128(16)

    ' Then
    ' 64 bit ids will never have more than 32 chars in hexadecimal representation
    Assert.that(Len(id)).isInRange(1, 32)
    Assert.that(id).matches("^[0-9a-f]+$", "i")
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call the printIdToString method
'  Then: returns a 64 bits unique id
'----------------------------------------------------------------
function DdUrlTransferTest__WhenGenerateUniqueIdDd_ThenGenerateAllId() as string
    ' Given

    ' When
    id = datadogroku_generateUniqueIdDd()

    ' Then
    Assert.that(id).hasSize(3)
    ' the full id always starts with the high id as both are hexadecimal representations
    Assert.that(id[0]).matches("^" + id[2] + "[0-9a-f]{16}$", "i")
    Assert.that(id[1]).matches("^[0-9]+$", "i")
    Assert.that(id[2]).matches("^[0-9a-f]+$", "i")
    return ""
end function

'----------------------------------------------------------------
' Given:
'  When: call the printIdToString method
'  Then: returns a 64 bits unique id
'----------------------------------------------------------------
function DdUrlTransferTest__WhenPrintIdToString_ThenGenerateStringId() as string
    ' some special cases / Decimal
    decRadix = 10
    Assert.that(datadogroku_printIdToString(0, 0, 0, 42, decRadix)).isEqualTo("42")
    Assert.that(datadogroku_printIdToString(0, 0, 16, 0, decRadix)).isEqualTo("68719476736")
    Assert.that(datadogroku_printIdToString(0, 815, 0, 0, decRadix)).isEqualTo("15034096420073284567040")
    Assert.that(datadogroku_printIdToString(23, 0, 13, 0, decRadix)).isEqualTo("1822247737828079764707345432576")

    ' some special cases / Hexadecimal
    hexRadix = 16
    Assert.that(datadogroku_printIdToString(0, 0, 0, 42, hexRadix)).isEqualTo("2a")
    Assert.that(datadogroku_printIdToString(0, 0, 16, 0, hexRadix)).isEqualTo("1000000000")
    Assert.that(datadogroku_printIdToString(0, 815, 0, 0, hexRadix)).isEqualTo("32f0000000000000000")
    Assert.that(datadogroku_printIdToString(23, 0, 0, 0, hexRadix)).isEqualTo("17000000000000000000000000")

    return ""
end function
