' Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
' This product includes software developed at Datadog (https://www.datadoghq.com/).
' Copyright 2022-Today Datadog, Inc.

import "pkg:/source/roku_modules/datadogroku/datadogSdk.brs"
import "pkg:/source/roku_modules/datadogroku/internalLogger.brs"
import "pkg:/source/roku_modules/datadogroku/timeUtils.brs"

sub init()
    datadogroku_ddLogThread("VideoScreen.init()")

    m.devTube = m.top.findNode("devTube")
    displaySize = CreateObject("roDeviceInfo").GetDisplaySize()
    ' center horizontally
    m.devTube.translation = [(displaySize.w - 1280) / 2, (displaySize.h - 720) / 2]

    setVideoContent()
end sub

function onKeyEvent(key as string, press as boolean) as boolean
    datadogroku_ddLogVerbose("VideoScreen.onKeyEvent(" + key + ", " + press.toStr() + ")")
    m.global.datadogLogsAgent@.logDebug("Key pressed", { screen: "Video", key: key, press: press })
    if(key = "play" and press)
        datadogroku_ddLogInfo("Video State: " + m.devTube.state)
        m.global.datadogRumAgent@.addAction({ target: "play", type: "click" })
        m.global.datadogRumAgent@.startOperation("playbackStart")
        m.devTube.control = "play"
        m.devTube.observeField("state", "onVideoStateChange")
        m.playbackStarted = false
    else if (key = "back" and press)
        if (m.playbackStarted = false)
            m.global.datadogRumAgent@.failOperation("playbackStart", "abandoned")
            m.devTube.unobserveField("state")
            m.devTube.unobserveField("position")
        end if
    end if
    return false
end function

sub setVideoContent()
    videoContent = createObject("RoSGNode", "ContentNode")
    videoContent.url = "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8"
    videoContent.title = "Test Video"
    videoContent.streamformat = "hls"

    m.devTube.content = videoContent
end sub

sub onVideoStateChange()
    state = m.devTube.state
    if (state = "playing")
        if (m.playbackStarted = false)
            m.global.datadogRumAgent@.succeedOperation("playbackStart")
        end if
        m.playbackStarted = true
        m.devTube.observeField("position", "onVideoPositionChange")
    else if (state = "error")
        m.playbackStarted = true
        m.global.datadogRumAgent@.failOperation("playbackStart", "error")
        m.devTube.unobserveField("position")
    else
        m.devTube.unobserveField("position")
    end if
end sub

sub onVideoPositionChange()
    m.global.datadogRumAgent@.reportUserActivity()
end sub
