' Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
' This product includes software developed at Datadog (https://www.datadoghq.com/).
' Copyright 2022-Today Datadog, Inc.

'----------------------------------------------------------------
' Main setup function.
' @return (object) a configured TestSuite object.
'----------------------------------------------------------------
function TestSuite__RumViewScope() as object
    this = BaseTestSuite()
    this.Name = "RumViewScope"

    this.addTest("WhenInit_ThenUpdateGlobalRumContext", RumViewScopeTest__WhenInit_ThenUpdateGlobalRumContext, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenGetContext_ThenReturnsContext", RumViewScopeTest__WhenGetContext_ThenReturnsContext, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenIsActive_ThenReturnsTrue", RumViewScopeTest__WhenIsActive_ThenReturnsTrue, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenStoppedIsActive_ThenReturnsFalse", RumViewScopeTest__WhenStoppedIsActive_ThenReturnsFalse, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)

    this.addTest("WhenHandleStopViewEvent_ThenWriteViewUpdate", RumViewScopeTest__WhenHandleStopViewEvent_ThenWriteViewUpdate, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleStopViewEventWithAction_ThenWriteViewUpdate", RumViewScopeTest__WhenHandleStopViewEventWithAction_ThenWriteViewUpdate, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleStopViewEventWithError_ThenWriteViewUpdate", RumViewScopeTest__WhenHandleStopViewEventWithError_ThenWriteViewUpdate, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleStopViewEventWithResource_ThenWriteViewUpdate", RumViewScopeTest__WhenHandleStopViewEventWithResource_ThenWriteViewUpdate, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleStopViewEventTwice_ThenWriteViewEvent", RumViewScopeTest__WhenHandleStopViewEventTwice_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleStartViewEvent_ThenWriteViewEvent", RumViewScopeTest__WhenHandleStartViewEvent_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenStopUnknownView_ThenDoNothing", RumViewScopeTest__WhenStopUnknownView_ThenDoNothing, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)

    this.addTest("WhenHandleAddErrorEvent_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddErrorEvent_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAddErrorEventWithContext_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddErrorEventWithContext_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAddErrorEventWithUserInfo_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddErrorEventWithUserInfo_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAddErrorEventWithAction_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddErrorEventWithAction_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleEmptyAddErrorEvent_ThenWriteViewEvent", RumViewScopeTest__WhenHandleEmptyAddErrorEvent_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)

    this.addTest("WhenHandleAddResourceEvent_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddResourceEvent_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAddResourceEventWithContext_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddResourceEventWithContext_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAddResourceEventWithUserInfo_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddResourceEventWithUserInfo_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAddResourceEventWithAction_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddResourceEventWithAction_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAddMinimalResourceEvent_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddMinimalResourceEvent_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)

    this.addTest("WhenHandleAddFailedResourceEvent_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddFailedResourceEvent_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAddFailedResourceEventWithContext_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddFailedResourceEventWithContext_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAddFailedResourceEventWithUserInfo_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddFailedResourceEventWithUserInfo_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAddFailedResourceEventWithAction_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddFailedResourceEventWithAction_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)

    this.addTest("WhenHandleAddActionEvent_ThenCreateChildScope", RumViewScopeTest__WhenHandleAddActionEvent_ThenCreateChildScope, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAddCustomActionEvent_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddCustomActionEvent_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAddCustomActionEventWithContext_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddCustomActionEventWithContext_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAddCustomActionEventWithUserInfo_ThenWriteViewEvent", RumViewScopeTest__WhenHandleAddCustomActionEventWithUserInfo_ThenWriteViewEvent, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)

    this.addTest("WhenHandleAnyEvent_ThenDelegateToActiveActionScope", RumViewScopeTest__WhenHandleAnyEvent_ThenDelegateToActiveActionScope, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleAnyEventActionNotActive_ThenDiscardIt", RumViewScopeTest__WhenHandleAnyEventActionNotActive_ThenDiscardIt, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)

    this.addTest("WhenHandleKeepAliveEvent_ThenWriteViewUpdate", RumViewScopeTest__WhenHandleKeepAliveEvent_ThenWriteViewUpdate, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleKeepAliveEventWithContext_ThenWriteViewUpdate", RumViewScopeTest__WhenHandleKeepAliveEventWithContext_ThenWriteViewUpdate, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)
    this.addTest("WhenHandleKeepAliveEventWithUserInfo_ThenWriteViewUpdate", RumViewScopeTest__WhenHandleKeepAliveEventWithUserInfo_ThenWriteViewUpdate, RumViewScopeTest__SetUp, RumViewScopeTest__TearDown)

    return this
end function

sub RumViewScopeTest__SetUp()
    ' Mocks
    m.testSuite.mockWriter = CreateObject("roSGNode", "MockWriterTask")
    m.testSuite.mockParentScope = CreateObject("roSGNode", "MockRumScope")
    m.testSuite.mockActionScope = CreateObject("roSGNode", "MockRumScope")

    ' Fake data
    m.testSuite.fakeViewName = IG_GetString(16)
    m.testSuite.fakeViewUrl = "https://" + IG_GetString(32)
    m.testSuite.fakeActionId = IG_GetString(32)
    m.testSuite.mockActionScope@.stubCall("getRumContext", {}, { actionId: m.testSuite.fakeActionId })
    m.testSuite.mockActionScope@.stubCall("isActive", {}, true)
    m.testSuite.fakeGlobalUserInfo = {
        id: IG_GetString(16),
        name: IG_GetString(16),
        email: IG_GetString(16) + "@" + IG_GetString(16) + ".com"
    }
    m.testSuite.fakeGlobalContext = {}
    for i = 1 to 5
        m.testSuite.fakeGlobalContext[IG_GetString(16) + i.toStr()] = IG_GetOneOf([IG_GetString(12), IG_GetInteger(), IG_GetFloat(), IG_GetBoolean()])
        m.testSuite.fakeGlobalUserInfo[IG_GetString(16) + i.toStr()] = IG_GetOneOf([IG_GetString(12), IG_GetInteger(), IG_GetFloat(), IG_GetBoolean()])
    end for
    m.testSuite.global.addFields({ datadogContext: {}, datadogUserInfo: {}, datadogRumContext: {} })

    ' Tested Task
    m.testSuite.startTimestamp& = datadogroku_getTimestamp()
    m.testSuite.testedScope = CreateObject("roSGNode", "datadogroku_RumViewScope")
    m.testSuite.testedScope.parentScope = m.testSuite.mockParentScope
    m.testSuite.testedScope.viewName = m.testSuite.fakeViewName
    m.testSuite.testedScope.viewUrl = m.testSuite.fakeViewUrl
end sub

sub RumViewScopeTest__TearDown()
    m.testSuite.Delete("mockWriter")
    m.testSuite.Delete("mockParentScope")
    m.testSuite.Delete("mockActionScope")
    m.testSuite.Delete("testedScope")
end sub

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: init
'  Then: check the global rum context is updated with the view id
'----------------------------------------------------------------
function RumViewScopeTest__WhenInit_ThenUpdateGlobalRumContext() as string
    ' When
    context = m.testedScope@.getRumContext()

    ' Then
    Assert.that(context.viewId).isEqualTo(m.global.datadogRumContext.viewId)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: requesting the rum context
'  Then: returns a rum context with parentScope's context plus sessionId
'----------------------------------------------------------------
function RumViewScopeTest__WhenGetContext_ThenReturnsContext() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeVersion = IG_GetString(16)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        applicationVersion: fakeVersion,
        sessionId: fakeSessionId
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)

    ' When
    context = m.testedScope@.getRumContext()

    ' Then
    Assert.that(context.applicationId).isEqualTo(fakeApplicationId)
    Assert.that(context.service).isEqualTo(fakeService)
    Assert.that(context.applicationVersion).isEqualTo(fakeVersion)
    Assert.that(context.sessionId).isEqualTo(fakeSessionId)
    Assert.that(context.viewId).isNotEmpty()
    Assert.that(context.viewName).isEqualTo(m.fakeViewName)
    Assert.that(context.viewUrl).isEqualTo(m.fakeViewUrl)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: calling isActive
'  Then: returns a true
'----------------------------------------------------------------
function RumViewScopeTest__WhenIsActive_ThenReturnsTrue() as string
    ' Given

    ' When
    isActive = m.testedScope@.isActive()

    ' Then
    Assert.that(isActive).isEqualTo(true)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: calling stop then isActive
'  Then: returns a false
'----------------------------------------------------------------
function RumViewScopeTest__WhenStoppedIsActive_ThenReturnsFalse() as string
    ' Given
    fakeEvent = { mock: "event", eventType: "stopView", viewName: m.fakeViewName, viewUrl: m.fakeViewUrl }

    ' When
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)
    isActive = m.testedScope@.isActive()

    ' Then
    Assert.that(isActive).isEqualTo(false)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (stopView)
'  Then: writes a view event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleStopViewEvent_ThenWriteViewUpdate() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeEvent = { mock: "event", eventType: "stopView", viewName: m.fakeViewName, viewUrl: m.fakeViewUrl }

    ' When
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    viewEvent = ParseJson(updates[0])
    Assert.that(viewEvent).isNotInvalid()
    Assert.that(viewEvent._dd.document_version).isEqualTo(1)
    Assert.that(viewEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(viewEvent.date).isInRange(m.startTimestamp&, m.startTimestamp& + 5)
    Assert.that(viewEvent.service).isEqualTo(fakeService)
    Assert.that(viewEvent.session.has_replay).isEqualTo(false)
    Assert.that(viewEvent.session.id).isNotEmpty()
    Assert.that(viewEvent.session.type).isEqualTo("user")
    Assert.that(viewEvent.source).isEqualTo("roku")
    Assert.that(viewEvent.type).isEqualTo("view")
    Assert.that(viewEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(viewEvent.view.id).isNotEmpty()
    Assert.that(viewEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(viewEvent.view.time_spent).isInRange(1000000, 10000000)
    Assert.that(viewEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(viewEvent.view.action.count).isEqualTo(0)
    Assert.that(viewEvent.view.error.count).isEqualTo(0)
    Assert.that(viewEvent.view.resource.count).isEqualTo(0)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (stopView) after an action
'  Then: writes a view event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleStopViewEventWithAction_ThenWriteViewUpdate() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeAction = { target: IG_GetString(16), type: IG_GetOneOf(["custom", "click", "tap", "scroll", "swipe", "application_start", "back"]) }
    fakeActionEvent = { mock: "event", eventType: "addAction", action: fakeAction }
    fakeEvent = { mock: "event", eventType: "stopView", viewName: m.fakeViewName, viewUrl: m.fakeViewUrl }

    ' When
    m.testedScope@.handleEvent(fakeActionEvent, m.mockWriter)
    sleep(40)
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(2)
    viewEvent = ParseJson(updates[1])
    Assert.that(viewEvent).isNotInvalid()
    Assert.that(viewEvent._dd.document_version).isEqualTo(1)
    Assert.that(viewEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(viewEvent.date).isInRange(m.startTimestamp&, m.startTimestamp& + 5)
    Assert.that(viewEvent.service).isEqualTo(fakeService)
    Assert.that(viewEvent.session.has_replay).isEqualTo(false)
    Assert.that(viewEvent.session.id).isNotEmpty()
    Assert.that(viewEvent.session.type).isEqualTo("user")
    Assert.that(viewEvent.source).isEqualTo("roku")
    Assert.that(viewEvent.type).isEqualTo("view")
    Assert.that(viewEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(viewEvent.view.id).isNotEmpty()
    Assert.that(viewEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(viewEvent.view.time_spent).isInRange(45000000, 100000000)
    Assert.that(viewEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(viewEvent.view.action.count).isEqualTo(1)
    Assert.that(viewEvent.view.error.count).isEqualTo(0)
    Assert.that(viewEvent.view.resource.count).isEqualTo(0)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (stopView) after an error
'  Then: writes a view event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleStopViewEventWithError_ThenWriteViewUpdate() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeException = { number: IG_GetInteger(255), message: IG_GetString(32), backtrace: IG_GetBacktrace() }
    fakeErrorEvent = { mock: "event", eventType: "addError", exception: fakeException }
    fakeEvent = { mock: "event", eventType: "stopView", viewName: m.fakeViewName, viewUrl: m.fakeViewUrl }

    ' When
    m.testedScope@.handleEvent(fakeErrorEvent, m.mockWriter)
    sleep(40)
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(2)
    viewEvent = ParseJson(updates[1])
    Assert.that(viewEvent).isNotInvalid()
    Assert.that(viewEvent._dd.document_version).isEqualTo(1)
    Assert.that(viewEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(viewEvent.date).isInRange(m.startTimestamp&, m.startTimestamp& + 10)
    Assert.that(viewEvent.service).isEqualTo(fakeService)
    Assert.that(viewEvent.session.has_replay).isEqualTo(false)
    Assert.that(viewEvent.session.id).isNotEmpty()
    Assert.that(viewEvent.session.type).isEqualTo("user")
    Assert.that(viewEvent.source).isEqualTo("roku")
    Assert.that(viewEvent.type).isEqualTo("view")
    Assert.that(viewEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(viewEvent.view.id).isNotEmpty()
    Assert.that(viewEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(viewEvent.view.time_spent).isInRange(45000000, 150000000)
    Assert.that(viewEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(viewEvent.view.action.count).isEqualTo(0)
    Assert.that(viewEvent.view.error.count).isEqualTo(1)
    Assert.that(viewEvent.view.resource.count).isEqualTo(0)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (stopView) after a resource
'  Then: writes a view event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleStopViewEventWithResource_ThenWriteViewUpdate() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeResource = { url: IG_GetString(32), method: IG_GetString(4), status: "ok", httpCode: IG_GetInteger(600), transferTime: IG_GetDouble() }
    fakeResourceEvent = { mock: "event", eventType: "addResource", resource: fakeResource }
    fakeEvent = { mock: "event", eventType: "stopView", viewName: m.fakeViewName, viewUrl: m.fakeViewUrl }

    ' When
    m.testedScope@.handleEvent(fakeResourceEvent, m.mockWriter)
    sleep(40)
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(2)
    viewEvent = ParseJson(updates[1])
    Assert.that(viewEvent).isNotInvalid()
    Assert.that(viewEvent._dd.document_version).isEqualTo(1)
    Assert.that(viewEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(viewEvent.date).isInRange(m.startTimestamp&, m.startTimestamp& + 5)
    Assert.that(viewEvent.service).isEqualTo(fakeService)
    Assert.that(viewEvent.session.has_replay).isEqualTo(false)
    Assert.that(viewEvent.session.id).isNotEmpty()
    Assert.that(viewEvent.session.type).isEqualTo("user")
    Assert.that(viewEvent.source).isEqualTo("roku")
    Assert.that(viewEvent.type).isEqualTo("view")
    Assert.that(viewEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(viewEvent.view.id).isNotEmpty()
    Assert.that(viewEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(viewEvent.view.time_spent).isInRange(45000000, 100000000)
    Assert.that(viewEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(viewEvent.view.action.count).isEqualTo(0)
    Assert.that(viewEvent.view.error.count).isEqualTo(0)
    Assert.that(viewEvent.view.resource.count).isEqualTo(1)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (stopView) twice
'  Then: write a view event but ignores the second stop
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleStopViewEventTwice_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeEvent = { mock: "event", eventType: "stopView", viewName: m.fakeViewName, viewUrl: m.fakeViewUrl }

    ' When
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    viewEvent = ParseJson(updates[0])
    Assert.that(viewEvent).isNotInvalid()
    Assert.that(viewEvent._dd.document_version).isEqualTo(1)
    Assert.that(viewEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(viewEvent.date).isInRange(m.startTimestamp&, m.startTimestamp& + 5)
    Assert.that(viewEvent.service).isEqualTo(fakeService)
    Assert.that(viewEvent.session.has_replay).isEqualTo(false)
    Assert.that(viewEvent.session.id).isNotEmpty()
    Assert.that(viewEvent.session.type).isEqualTo("user")
    Assert.that(viewEvent.source).isEqualTo("roku")
    Assert.that(viewEvent.type).isEqualTo("view")
    Assert.that(viewEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(viewEvent.view.id).isNotEmpty()
    Assert.that(viewEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(viewEvent.view.time_spent).isInRange(1000000, 10000000)
    Assert.that(viewEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(viewEvent.view.action.count).isEqualTo(0)
    Assert.that(viewEvent.view.error.count).isEqualTo(0)
    Assert.that(viewEvent.view.resource.count).isEqualTo(0)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (stopView for an unknown view)
'  Then: do nothing
'----------------------------------------------------------------
function RumViewScopeTest__WhenStopUnknownView_ThenDoNothing() as string
    ' Given
    fakeEvent = { mock: "event", eventType: "stopView", viewName: m.fakeViewName + IG_GetString(8), viewUrl: m.fakeViewUrl + IG_GetString(8) }

    ' When
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(0)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (startView) twice
'  Then: write a view event and consider this view stopped
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleStartViewEvent_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeEvent = { mock: "event", eventType: "startView", viewName: IG_GetString(32), viewUrl: IG_GetString(32) }

    ' When
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    viewEvent = ParseJson(updates[0])
    Assert.that(viewEvent).isNotInvalid()
    Assert.that(viewEvent._dd.document_version).isEqualTo(1)
    Assert.that(viewEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(viewEvent.date).isInRange(m.startTimestamp&, m.startTimestamp& + 5)
    Assert.that(viewEvent.service).isEqualTo(fakeService)
    Assert.that(viewEvent.session.has_replay).isEqualTo(false)
    Assert.that(viewEvent.session.id).isNotEmpty()
    Assert.that(viewEvent.session.type).isEqualTo("user")
    Assert.that(viewEvent.source).isEqualTo("roku")
    Assert.that(viewEvent.type).isEqualTo("view")
    Assert.that(viewEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(viewEvent.view.id).isNotEmpty()
    Assert.that(viewEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(viewEvent.view.time_spent).isInRange(1000000, 20000000)
    Assert.that(viewEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(viewEvent.view.action.count).isEqualTo(0)
    Assert.that(viewEvent.view.error.count).isEqualTo(0)
    Assert.that(viewEvent.view.resource.count).isEqualTo(0)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (addError)
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddErrorEvent_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeMessage = IG_GetString(128)
    fakeErrorNumber = IG_GetInteger(256)
    fakeBacktrace = IG_GetBacktrace()
    fakeException = { number: fakeErrorNumber, message: fakeMessage, backtrace: fakeBacktrace }
    fakeEvent = { mock: "event", eventType: "addError", exception: fakeException }

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    errorEvent = ParseJson(updates[0])
    Assert.that(errorEvent).isNotInvalid()
    Assert.that(errorEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(errorEvent.action.id).isEqualTo(invalid)
    Assert.that(errorEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 5)
    Assert.that(errorEvent.service).isEqualTo(fakeService)
    Assert.that(errorEvent.session.has_replay).isEqualTo(false)
    Assert.that(errorEvent.session.id).isNotEmpty()
    Assert.that(errorEvent.session.type).isEqualTo("user")
    Assert.that(errorEvent.source).isEqualTo("roku")
    Assert.that(errorEvent.type).isEqualTo("error")
    Assert.that(errorEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(errorEvent.view.id).isNotEmpty()
    Assert.that(errorEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(errorEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(errorEvent.error.id).isNotEmpty()
    Assert.that(errorEvent.error.message).isEqualTo(fakeMessage)
    Assert.that(errorEvent.error.source).isEqualTo("source")
    Assert.that(errorEvent.error.source_type).isEqualTo("roku")
    Assert.that(errorEvent.error.stack).isEqualTo(datadogroku_backtraceToString(fakeBacktrace))
    Assert.that(errorEvent.error.is_crash).isEqualTo(false)
    Assert.that(errorEvent.error.type).isEqualTo("&h" + datadogroku_decToHex(fakeErrorNumber))
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope and a global rum context
'  When: handling an event (addError)
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddErrorEventWithContext_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeMessage = IG_GetString(128)
    fakeErrorNumber = IG_GetInteger(256)
    fakeBacktrace = IG_GetBacktrace()
    fakeException = { number: fakeErrorNumber, message: fakeMessage, backtrace: fakeBacktrace }
    fakeEvent = { mock: "event", eventType: "addError", exception: fakeException }
    m.global.setField("datadogContext", m.fakeGlobalContext)

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    errorEvent = ParseJson(updates[0])
    Assert.that(errorEvent).isNotInvalid()
    Assert.that(errorEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(errorEvent.action.id).isEqualTo(invalid)
    Assert.that(errorEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 5)
    Assert.that(errorEvent.service).isEqualTo(fakeService)
    Assert.that(errorEvent.session.has_replay).isEqualTo(false)
    Assert.that(errorEvent.session.id).isNotEmpty()
    Assert.that(errorEvent.session.type).isEqualTo("user")
    Assert.that(errorEvent.source).isEqualTo("roku")
    Assert.that(errorEvent.type).isEqualTo("error")
    Assert.that(errorEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(errorEvent.view.id).isNotEmpty()
    Assert.that(errorEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(errorEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(errorEvent.error.id).isNotEmpty()
    Assert.that(errorEvent.error.message).isEqualTo(fakeMessage)
    Assert.that(errorEvent.error.source).isEqualTo("source")
    Assert.that(errorEvent.error.source_type).isEqualTo("roku")
    Assert.that(errorEvent.error.stack).isEqualTo(datadogroku_backtraceToString(fakeBacktrace))
    Assert.that(errorEvent.error.is_crash).isEqualTo(false)
    Assert.that(errorEvent.error.type).isEqualTo("&h" + datadogroku_decToHex(fakeErrorNumber))
    Assert.that(errorEvent.context).isEqualTo(m.fakeGlobalContext)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope and a global user info
'  When: handling an event (addError)
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddErrorEventWithUserInfo_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeMessage = IG_GetString(128)
    fakeErrorNumber = IG_GetInteger(256)
    fakeBacktrace = IG_GetBacktrace()
    fakeException = { number: fakeErrorNumber, message: fakeMessage, backtrace: fakeBacktrace }
    fakeEvent = { mock: "event", eventType: "addError", exception: fakeException }
    m.global.setField("datadogUserInfo", m.fakeGlobalUserInfo)

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    errorEvent = ParseJson(updates[0])
    Assert.that(errorEvent).isNotInvalid()
    Assert.that(errorEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(errorEvent.action.id).isEqualTo(invalid)
    Assert.that(errorEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 5)
    Assert.that(errorEvent.service).isEqualTo(fakeService)
    Assert.that(errorEvent.session.has_replay).isEqualTo(false)
    Assert.that(errorEvent.session.id).isNotEmpty()
    Assert.that(errorEvent.session.type).isEqualTo("user")
    Assert.that(errorEvent.source).isEqualTo("roku")
    Assert.that(errorEvent.type).isEqualTo("error")
    Assert.that(errorEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(errorEvent.view.id).isNotEmpty()
    Assert.that(errorEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(errorEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(errorEvent.error.id).isNotEmpty()
    Assert.that(errorEvent.error.message).isEqualTo(fakeMessage)
    Assert.that(errorEvent.error.source).isEqualTo("source")
    Assert.that(errorEvent.error.source_type).isEqualTo("roku")
    Assert.that(errorEvent.error.stack).isEqualTo(datadogroku_backtraceToString(fakeBacktrace))
    Assert.that(errorEvent.error.is_crash).isEqualTo(false)
    Assert.that(errorEvent.error.type).isEqualTo("&h" + datadogroku_decToHex(fakeErrorNumber))
    Assert.that(errorEvent.usr).isEqualTo(m.fakeGlobalUserInfo)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (addError) with an active action
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddErrorEventWithAction_ThenWriteViewEvent() as string
    ' Given
    m.testedScope.activeAction = m.mockActionScope
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeMessage = IG_GetString(128)
    fakeErrorNumber = IG_GetInteger(256)
    fakeBacktrace = IG_GetBacktrace()
    fakeException = { number: fakeErrorNumber, message: fakeMessage, backtrace: fakeBacktrace }
    fakeEvent = { mock: "event", eventType: "addError", exception: fakeException }

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    errorEvent = ParseJson(updates[0])
    Assert.that(errorEvent).isNotInvalid()
    Assert.that(errorEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(errorEvent.action.id).isEqualTo(m.fakeActionId)
    Assert.that(errorEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 10)
    Assert.that(errorEvent.service).isEqualTo(fakeService)
    Assert.that(errorEvent.session.has_replay).isEqualTo(false)
    Assert.that(errorEvent.session.id).isNotEmpty()
    Assert.that(errorEvent.session.type).isEqualTo("user")
    Assert.that(errorEvent.source).isEqualTo("roku")
    Assert.that(errorEvent.type).isEqualTo("error")
    Assert.that(errorEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(errorEvent.view.id).isNotEmpty()
    Assert.that(errorEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(errorEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(errorEvent.error.id).isNotEmpty()
    Assert.that(errorEvent.error.message).isEqualTo(fakeMessage)
    Assert.that(errorEvent.error.source).isEqualTo("source")
    Assert.that(errorEvent.error.source_type).isEqualTo("roku")
    Assert.that(errorEvent.error.stack).isEqualTo(datadogroku_backtraceToString(fakeBacktrace))
    Assert.that(errorEvent.error.is_crash).isEqualTo(false)
    Assert.that(errorEvent.error.type).isEqualTo("&h" + datadogroku_decToHex(fakeErrorNumber))
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (addError) with missing exception fields
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleEmptyAddErrorEvent_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeEvent = { mock: "event", eventType: "addError", exception: {} }

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    errorEvent = ParseJson(updates[0])
    Assert.that(errorEvent).isNotInvalid()
    Assert.that(errorEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(errorEvent.action.id).isEqualTo(invalid)
    Assert.that(errorEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 5)
    Assert.that(errorEvent.service).isEqualTo(fakeService)
    Assert.that(errorEvent.session.has_replay).isEqualTo(false)
    Assert.that(errorEvent.session.id).isNotEmpty()
    Assert.that(errorEvent.session.type).isEqualTo("user")
    Assert.that(errorEvent.source).isEqualTo("roku")
    Assert.that(errorEvent.type).isEqualTo("error")
    Assert.that(errorEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(errorEvent.view.id).isNotEmpty()
    Assert.that(errorEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(errorEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(errorEvent.error.id).isNotEmpty()
    Assert.that(errorEvent.error.message).isEqualTo("Unknown exception")
    Assert.that(errorEvent.error.source).isEqualTo("source")
    Assert.that(errorEvent.error.source_type).isEqualTo("roku")
    Assert.that(errorEvent.error.stack).isEqualTo(invalid)
    Assert.that(errorEvent.error.is_crash).isEqualTo(false)
    Assert.that(errorEvent.error.type).isEqualTo("unknown")
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (addResource) ok
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddResourceEvent_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeResourceUrl = IG_GetString(128)
    fakeMethod = IG_GetOneOf(["GET", "POST", "HEAD", "PUT"])
    fakeHttpCode = IG_GetInteger(600)
    fakeDurationNs& = IG_GetInteger()
    nsToSec# = 1000000000
    fakeTransferTime# = fakeDurationNs& / nsToSec#
    fakeSize = IG_GetInteger()
    fakeResource = { url: fakeResourceUrl, method: fakeMethod, status: "ok", httpCode: fakeHttpCode, transferTime: fakeTransferTime#, bytesDownloaded: fakeSize }
    fakeEvent = { mock: "event", eventType: "addResource", resource: fakeResource }

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    resourceEvent = ParseJson(updates[0])
    Assert.that(resourceEvent).isNotInvalid()
    Assert.that(resourceEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(resourceEvent.action.id).isEqualTo(invalid)
    Assert.that(resourceEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 5)
    Assert.that(resourceEvent.service).isEqualTo(fakeService)
    Assert.that(resourceEvent.session.has_replay).isEqualTo(false)
    Assert.that(resourceEvent.session.id).isNotEmpty()
    Assert.that(resourceEvent.session.type).isEqualTo("user")
    Assert.that(resourceEvent.source).isEqualTo("roku")
    Assert.that(resourceEvent.type).isEqualTo("resource")
    Assert.that(resourceEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(resourceEvent.view.id).isNotEmpty()
    Assert.that(resourceEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(resourceEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(resourceEvent.resource.id).isNotEmpty()
    Assert.that(resourceEvent.resource.type).isEqualTo("native")
    Assert.that(resourceEvent.resource.method).isEqualTo(fakeMethod)
    Assert.that(resourceEvent.resource.url).isEqualTo(fakeResourceUrl)
    Assert.that(resourceEvent.resource.status_code).isEqualTo(fakeHttpCode)
    Assert.that(resourceEvent.resource.duration).isInRange(fakeDurationNs& - 1000, fakeDurationNs& + 1000)
    Assert.that(resourceEvent.resource.size).isEqualTo(fakeSize)
    ' TODO RUMM-2529 assert traceId and spanId
    ' TODO RUMM-2530 assert timings (dns, ssl, …)?
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope and a global rum context
'  When: handling an event (addResource) ok
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddResourceEventWithContext_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeResourceUrl = IG_GetString(128)
    fakeMethod = IG_GetOneOf(["GET", "POST", "HEAD", "PUT"])
    fakeHttpCode = IG_GetInteger(600)
    fakeDurationNs& = IG_GetInteger()
    nsToSec# = 1000000000
    fakeTransferTime# = fakeDurationNs& / nsToSec#
    fakeSize = IG_GetInteger()
    fakeResource = { url: fakeResourceUrl, method: fakeMethod, status: "ok", httpCode: fakeHttpCode, transferTime: fakeTransferTime#, bytesDownloaded: fakeSize }
    fakeEvent = { mock: "event", eventType: "addResource", resource: fakeResource }
    m.global.setField("datadogContext", m.fakeGlobalContext)

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    resourceEvent = ParseJson(updates[0])
    Assert.that(resourceEvent).isNotInvalid()
    Assert.that(resourceEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(resourceEvent.action.id).isEqualTo(invalid)
    Assert.that(resourceEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 5)
    Assert.that(resourceEvent.service).isEqualTo(fakeService)
    Assert.that(resourceEvent.session.has_replay).isEqualTo(false)
    Assert.that(resourceEvent.session.id).isNotEmpty()
    Assert.that(resourceEvent.session.type).isEqualTo("user")
    Assert.that(resourceEvent.source).isEqualTo("roku")
    Assert.that(resourceEvent.type).isEqualTo("resource")
    Assert.that(resourceEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(resourceEvent.view.id).isNotEmpty()
    Assert.that(resourceEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(resourceEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(resourceEvent.resource.id).isNotEmpty()
    Assert.that(resourceEvent.resource.type).isEqualTo("native")
    Assert.that(resourceEvent.resource.method).isEqualTo(fakeMethod)
    Assert.that(resourceEvent.resource.url).isEqualTo(fakeResourceUrl)
    Assert.that(resourceEvent.resource.status_code).isEqualTo(fakeHttpCode)
    Assert.that(resourceEvent.resource.duration).isInRange(fakeDurationNs& - 1000, fakeDurationNs& + 1000)
    Assert.that(resourceEvent.resource.size).isEqualTo(fakeSize)
    Assert.that(resourceEvent.context).isEqualTo(m.fakeGlobalContext)
    ' TODO RUMM-2529 assert traceId and spanId
    ' TODO RUMM-2530 assert timings (dns, ssl, …)?
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope and a global user info
'  When: handling an event (addResource) ok
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddResourceEventWithUserInfo_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeResourceUrl = IG_GetString(128)
    fakeMethod = IG_GetOneOf(["GET", "POST", "HEAD", "PUT"])
    fakeHttpCode = IG_GetInteger(600)
    fakeDurationNs& = IG_GetInteger()
    nsToSec# = 1000000000
    fakeTransferTime# = fakeDurationNs& / nsToSec#
    fakeSize = IG_GetInteger()
    fakeResource = { url: fakeResourceUrl, method: fakeMethod, status: "ok", httpCode: fakeHttpCode, transferTime: fakeTransferTime#, bytesDownloaded: fakeSize }
    fakeEvent = { mock: "event", eventType: "addResource", resource: fakeResource }
    m.global.setField("datadogUserInfo", m.fakeGlobalUserInfo)

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    resourceEvent = ParseJson(updates[0])
    Assert.that(resourceEvent).isNotInvalid()
    Assert.that(resourceEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(resourceEvent.action.id).isEqualTo(invalid)
    Assert.that(resourceEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 5)
    Assert.that(resourceEvent.service).isEqualTo(fakeService)
    Assert.that(resourceEvent.session.has_replay).isEqualTo(false)
    Assert.that(resourceEvent.session.id).isNotEmpty()
    Assert.that(resourceEvent.session.type).isEqualTo("user")
    Assert.that(resourceEvent.source).isEqualTo("roku")
    Assert.that(resourceEvent.type).isEqualTo("resource")
    Assert.that(resourceEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(resourceEvent.view.id).isNotEmpty()
    Assert.that(resourceEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(resourceEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(resourceEvent.resource.id).isNotEmpty()
    Assert.that(resourceEvent.resource.type).isEqualTo("native")
    Assert.that(resourceEvent.resource.method).isEqualTo(fakeMethod)
    Assert.that(resourceEvent.resource.url).isEqualTo(fakeResourceUrl)
    Assert.that(resourceEvent.resource.status_code).isEqualTo(fakeHttpCode)
    Assert.that(resourceEvent.resource.duration).isInRange(fakeDurationNs& - 1000, fakeDurationNs& + 1000)
    Assert.that(resourceEvent.resource.size).isEqualTo(fakeSize)
    Assert.that(resourceEvent.usr).isEqualTo(m.fakeGlobalUserInfo)
    ' TODO RUMM-2529 assert traceId and spanId
    ' TODO RUMM-2530 assert timings (dns, ssl, …)?
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (addResource) with an active action
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddResourceEventWithAction_ThenWriteViewEvent() as string
    ' Given
    m.testedScope.activeAction = m.mockActionScope
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeResourceUrl = IG_GetString(128)
    fakeMethod = IG_GetOneOf(["GET", "POST", "HEAD", "PUT"])
    fakeHttpCode = IG_GetInteger(600)
    fakeDurationNs& = IG_GetInteger()
    nsToSec# = 1000000000
    fakeTransferTime# = fakeDurationNs& / nsToSec#
    fakeSize = IG_GetInteger()
    fakeResource = { url: fakeResourceUrl, method: fakeMethod, status: "ok", httpCode: fakeHttpCode, transferTime: fakeTransferTime#, bytesDownloaded: fakeSize }
    fakeEvent = { mock: "event", eventType: "addResource", resource: fakeResource }

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    resourceEvent = ParseJson(updates[0])
    Assert.that(resourceEvent).isNotInvalid()
    Assert.that(resourceEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(resourceEvent.action.id).isEqualTo(m.fakeActionId)
    Assert.that(resourceEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 5)
    Assert.that(resourceEvent.service).isEqualTo(fakeService)
    Assert.that(resourceEvent.session.has_replay).isEqualTo(false)
    Assert.that(resourceEvent.session.id).isNotEmpty()
    Assert.that(resourceEvent.session.type).isEqualTo("user")
    Assert.that(resourceEvent.source).isEqualTo("roku")
    Assert.that(resourceEvent.type).isEqualTo("resource")
    Assert.that(resourceEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(resourceEvent.view.id).isNotEmpty()
    Assert.that(resourceEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(resourceEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(resourceEvent.resource.id).isNotEmpty()
    Assert.that(resourceEvent.resource.type).isEqualTo("native")
    Assert.that(resourceEvent.resource.method).isEqualTo(fakeMethod)
    Assert.that(resourceEvent.resource.url).isEqualTo(fakeResourceUrl)
    Assert.that(resourceEvent.resource.status_code).isEqualTo(fakeHttpCode)
    Assert.that(resourceEvent.resource.duration).isInRange(fakeDurationNs& - 1000, fakeDurationNs& + 1000)
    Assert.that(resourceEvent.resource.size).isEqualTo(fakeSize)
    ' TODO RUMM-2529 assert traceId and spanId
    ' TODO RUMM-2530 assert timings (dns, ssl, …)?
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (addResource) ok
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddMinimalResourceEvent_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)

    fakeResourceUrl = IG_GetString(128)
    fakeDurationNs& = IG_GetInteger()
    nsToSec# = 1000000000
    fakeTransferTime# = fakeDurationNs& / nsToSec#
    fakeResource = { url: fakeResourceUrl, transferTime: fakeTransferTime# }
    fakeEvent = { mock: "event", eventType: "addResource", resource: fakeResource }

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    resourceEvent = ParseJson(updates[0])
    Assert.that(resourceEvent).isNotInvalid()
    Assert.that(resourceEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(resourceEvent.action.id).isEqualTo(invalid)
    Assert.that(resourceEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 5)
    Assert.that(resourceEvent.service).isEqualTo(fakeService)
    Assert.that(resourceEvent.session.has_replay).isEqualTo(false)
    Assert.that(resourceEvent.session.id).isNotEmpty()
    Assert.that(resourceEvent.session.type).isEqualTo("user")
    Assert.that(resourceEvent.source).isEqualTo("roku")
    Assert.that(resourceEvent.type).isEqualTo("resource")
    Assert.that(resourceEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(resourceEvent.view.id).isNotEmpty()
    Assert.that(resourceEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(resourceEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(resourceEvent.resource.id).isNotEmpty()
    Assert.that(resourceEvent.resource.type).isEqualTo("native")
    Assert.that(resourceEvent.resource.method).isEqualTo(invalid)
    Assert.that(resourceEvent.resource.url).isEqualTo(fakeResourceUrl)
    Assert.that(resourceEvent.resource.status_code).isEqualTo(invalid)
    Assert.that(resourceEvent.resource.duration).isInRange(fakeDurationNs& - 1000, fakeDurationNs& + 1000)
    Assert.that(resourceEvent.resource.size).isEqualTo(invalid)
    ' TODO RUMM-2529 assert traceId and spanId
    ' TODO RUMM-2530 assert timings (dns, ssl, …)?
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (addResource) failed
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddFailedResourceEvent_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeResourceUrl = IG_GetString(128)
    fakeMethod = IG_GetOneOf(["GET", "POST", "HEAD", "PUT"])
    fakeStatus = IG_GetOneOf([
        "unknownerror",
        "dnsfailure",
        "dnstimeout",
        "noroutetohost",
        "connectiontimeout",
        "connectionrefused",
        "untrustedcert",
        "expiredcert",
        "nocipher",
        "handshakefailed",
        "generalsocketerror",
        "httperror"
    ])
    fakeResource = { url: fakeResourceUrl, method: fakeMethod, status: fakeStatus }
    fakeEvent = { mock: "event", eventType: "addResource", resource: fakeResource }

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    errorEvent = ParseJson(updates[0])
    Assert.that(errorEvent).isNotInvalid()
    Assert.that(errorEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(errorEvent.action.id).isEqualTo(invalid)
    Assert.that(errorEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 5)
    Assert.that(errorEvent.service).isEqualTo(fakeService)
    Assert.that(errorEvent.session.has_replay).isEqualTo(false)
    Assert.that(errorEvent.session.id).isNotEmpty()
    Assert.that(errorEvent.session.type).isEqualTo("user")
    Assert.that(errorEvent.source).isEqualTo("roku")
    Assert.that(errorEvent.type).isEqualTo("error")
    Assert.that(errorEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(errorEvent.view.id).isNotEmpty()
    Assert.that(errorEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(errorEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(errorEvent.error.id).isNotEmpty()
    Assert.that(errorEvent.error.message).isEqualTo("Failed to perform request")
    Assert.that(errorEvent.error.source).isEqualTo("network")
    Assert.that(errorEvent.error.source_type).isEqualTo("roku")
    Assert.that(errorEvent.error.stack).isEqualTo(invalid)
    Assert.that(errorEvent.error.is_crash).isEqualTo(false)
    Assert.that(errorEvent.error.type).isEqualTo(fakeStatus)
    Assert.that(errorEvent.error.resource.type).isEqualTo("native")
    Assert.that(errorEvent.error.resource.method).isEqualTo(fakeMethod)
    Assert.that(errorEvent.error.resource.url).isEqualTo(fakeResourceUrl)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope and a global rum context
'  When: handling an event (addResource) failed
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddFailedResourceEventWithContext_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeResourceUrl = IG_GetString(128)
    fakeMethod = IG_GetOneOf(["GET", "POST", "HEAD", "PUT"])
    fakeStatus = IG_GetOneOf([
        "unknownerror",
        "dnsfailure",
        "dnstimeout",
        "noroutetohost",
        "connectiontimeout",
        "connectionrefused",
        "untrustedcert",
        "expiredcert",
        "nocipher",
        "handshakefailed",
        "generalsocketerror",
        "httperror"
    ])
    fakeResource = { url: fakeResourceUrl, method: fakeMethod, status: fakeStatus }
    fakeEvent = { mock: "event", eventType: "addResource", resource: fakeResource }
    m.global.setField("datadogContext", m.fakeGlobalContext)

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    errorEvent = ParseJson(updates[0])
    Assert.that(errorEvent).isNotInvalid()
    Assert.that(errorEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(errorEvent.action.id).isEqualTo(invalid)
    Assert.that(errorEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 5)
    Assert.that(errorEvent.service).isEqualTo(fakeService)
    Assert.that(errorEvent.session.has_replay).isEqualTo(false)
    Assert.that(errorEvent.session.id).isNotEmpty()
    Assert.that(errorEvent.session.type).isEqualTo("user")
    Assert.that(errorEvent.source).isEqualTo("roku")
    Assert.that(errorEvent.type).isEqualTo("error")
    Assert.that(errorEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(errorEvent.view.id).isNotEmpty()
    Assert.that(errorEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(errorEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(errorEvent.error.id).isNotEmpty()
    Assert.that(errorEvent.error.message).isEqualTo("Failed to perform request")
    Assert.that(errorEvent.error.source).isEqualTo("network")
    Assert.that(errorEvent.error.source_type).isEqualTo("roku")
    Assert.that(errorEvent.error.stack).isEqualTo(invalid)
    Assert.that(errorEvent.error.is_crash).isEqualTo(false)
    Assert.that(errorEvent.error.type).isEqualTo(fakeStatus)
    Assert.that(errorEvent.error.resource.type).isEqualTo("native")
    Assert.that(errorEvent.error.resource.method).isEqualTo(fakeMethod)
    Assert.that(errorEvent.error.resource.url).isEqualTo(fakeResourceUrl)
    Assert.that(errorEvent.context).isEqualTo(m.fakeGlobalContext)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope and a global user info
'  When: handling an event (addResource) failed
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddFailedResourceEventWithUserInfo_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeResourceUrl = IG_GetString(128)
    fakeMethod = IG_GetOneOf(["GET", "POST", "HEAD", "PUT"])
    fakeStatus = IG_GetOneOf([
        "unknownerror",
        "dnsfailure",
        "dnstimeout",
        "noroutetohost",
        "connectiontimeout",
        "connectionrefused",
        "untrustedcert",
        "expiredcert",
        "nocipher",
        "handshakefailed",
        "generalsocketerror",
        "httperror"
    ])
    fakeResource = { url: fakeResourceUrl, method: fakeMethod, status: fakeStatus }
    fakeEvent = { mock: "event", eventType: "addResource", resource: fakeResource }
    m.global.setField("datadogUserInfo", m.fakeGlobalUserInfo)

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    errorEvent = ParseJson(updates[0])
    Assert.that(errorEvent).isNotInvalid()
    Assert.that(errorEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(errorEvent.action.id).isEqualTo(invalid)
    Assert.that(errorEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 5)
    Assert.that(errorEvent.service).isEqualTo(fakeService)
    Assert.that(errorEvent.session.has_replay).isEqualTo(false)
    Assert.that(errorEvent.session.id).isNotEmpty()
    Assert.that(errorEvent.session.type).isEqualTo("user")
    Assert.that(errorEvent.source).isEqualTo("roku")
    Assert.that(errorEvent.type).isEqualTo("error")
    Assert.that(errorEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(errorEvent.view.id).isNotEmpty()
    Assert.that(errorEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(errorEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(errorEvent.error.id).isNotEmpty()
    Assert.that(errorEvent.error.message).isEqualTo("Failed to perform request")
    Assert.that(errorEvent.error.source).isEqualTo("network")
    Assert.that(errorEvent.error.source_type).isEqualTo("roku")
    Assert.that(errorEvent.error.stack).isEqualTo(invalid)
    Assert.that(errorEvent.error.is_crash).isEqualTo(false)
    Assert.that(errorEvent.error.type).isEqualTo(fakeStatus)
    Assert.that(errorEvent.error.resource.type).isEqualTo("native")
    Assert.that(errorEvent.error.resource.method).isEqualTo(fakeMethod)
    Assert.that(errorEvent.error.resource.url).isEqualTo(fakeResourceUrl)
    Assert.that(errorEvent.usr).isEqualTo(m.fakeGlobalUserInfo)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (addResource) failed with an active action
'  Then: write an error event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddFailedResourceEventWithAction_ThenWriteViewEvent() as string
    ' Given
    m.testedScope.activeAction = m.mockActionScope
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeResourceUrl = IG_GetString(128)
    fakeMethod = IG_GetOneOf(["GET", "POST", "HEAD", "PUT"])
    fakeStatus = IG_GetOneOf([
        "unknownerror",
        "dnsfailure",
        "dnstimeout",
        "noroutetohost",
        "connectiontimeout",
        "connectionrefused",
        "untrustedcert",
        "expiredcert",
        "nocipher",
        "handshakefailed",
        "generalsocketerror",
        "httperror"
    ])
    fakeResource = { url: fakeResourceUrl, method: fakeMethod, status: fakeStatus }
    fakeEvent = { mock: "event", eventType: "addResource", resource: fakeResource }

    ' When
    errorTimestamp& = datadogroku_getTimestamp()
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    errorEvent = ParseJson(updates[0])
    Assert.that(errorEvent).isNotInvalid()
    Assert.that(errorEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(errorEvent.action.id).isEqualTo(m.fakeActionId)
    Assert.that(errorEvent.date).isInRange(errorTimestamp&, errorTimestamp& + 5)
    Assert.that(errorEvent.service).isEqualTo(fakeService)
    Assert.that(errorEvent.session.has_replay).isEqualTo(false)
    Assert.that(errorEvent.session.id).isNotEmpty()
    Assert.that(errorEvent.session.type).isEqualTo("user")
    Assert.that(errorEvent.source).isEqualTo("roku")
    Assert.that(errorEvent.type).isEqualTo("error")
    Assert.that(errorEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(errorEvent.view.id).isNotEmpty()
    Assert.that(errorEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(errorEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(errorEvent.error.id).isNotEmpty()
    Assert.that(errorEvent.error.message).isEqualTo("Failed to perform request")
    Assert.that(errorEvent.error.source).isEqualTo("network")
    Assert.that(errorEvent.error.source_type).isEqualTo("roku")
    Assert.that(errorEvent.error.stack).isEqualTo(invalid)
    Assert.that(errorEvent.error.is_crash).isEqualTo(false)
    Assert.that(errorEvent.error.type).isEqualTo(fakeStatus)
    Assert.that(errorEvent.error.resource.type).isEqualTo("native")
    Assert.that(errorEvent.error.resource.method).isEqualTo(fakeMethod)
    Assert.that(errorEvent.error.resource.url).isEqualTo(fakeResourceUrl)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (addAction)
'  Then: create a child action scope
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddActionEvent_ThenCreateChildScope() as string
    ' Given
    fakeAction = { target: IG_GetString(16), type: IG_GetOneOf(["click", "tap", "scroll", "swipe", "application_start", "back"]) }
    fakeEvent = { mock: "event", eventType: "addAction", action: fakeAction }

    ' When
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    actionScope = m.testedScope.activeAction
    Assert.that(type(actionScope)).isEqualTo("roSGNode")
    Assert.that(actionScope.subType()).isEqualTo("datadogroku_RumActionScope")
    Assert.that(actionScope.target).isEqualTo(fakeAction.target)
    Assert.that(actionScope.actionType).isEqualTo(fakeAction.type)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (addAction) type=custom
'  Then: write a custom action event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddCustomActionEvent_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeAction = { target: IG_GetString(16), type: "custom" }
    fakeEvent = { mock: "event", eventType: "addAction", action: fakeAction }

    ' When
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)
    sleep(50)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    actionEvent = ParseJson(updates[0])
    Assert.that(actionEvent).isNotInvalid()
    Assert.that(actionEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(actionEvent.date).isInRange(m.startTimestamp&, m.startTimestamp& + 50)
    Assert.that(actionEvent.service).isEqualTo(fakeService)
    Assert.that(actionEvent.session.has_replay).isEqualTo(false)
    Assert.that(actionEvent.session.id).isNotEmpty()
    Assert.that(actionEvent.session.type).isEqualTo("user")
    Assert.that(actionEvent.source).isEqualTo("roku")
    Assert.that(actionEvent.type).isEqualTo("action")
    Assert.that(actionEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(actionEvent.view.id).isNotEmpty()
    Assert.that(actionEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(actionEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(actionEvent.action.id).isNotEmpty()
    Assert.that(actionEvent.action.type).isEqualTo("custom")
    Assert.that(actionEvent.action.loading_time).isEqualTo(0)
    Assert.that(actionEvent.action.target.name).isEqualTo(fakeAction.target)
    Assert.that(actionEvent.action.error.count).isEqualTo(0)
    Assert.that(actionEvent.action.resource.count).isEqualTo(0)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope and a global rum context
'  When: handling an event (addAction) type=custom
'  Then: write a custom action event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddCustomActionEventWithContext_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeAction = { target: IG_GetString(16), type: "custom" }
    fakeEvent = { mock: "event", eventType: "addAction", action: fakeAction }
    m.global.setField("datadogContext", m.fakeGlobalContext)

    ' When
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)
    sleep(50)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    actionEvent = ParseJson(updates[0])
    Assert.that(actionEvent).isNotInvalid()
    Assert.that(actionEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(actionEvent.date).isInRange(m.startTimestamp&, m.startTimestamp& + 50)
    Assert.that(actionEvent.service).isEqualTo(fakeService)
    Assert.that(actionEvent.session.has_replay).isEqualTo(false)
    Assert.that(actionEvent.session.id).isNotEmpty()
    Assert.that(actionEvent.session.type).isEqualTo("user")
    Assert.that(actionEvent.source).isEqualTo("roku")
    Assert.that(actionEvent.type).isEqualTo("action")
    Assert.that(actionEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(actionEvent.view.id).isNotEmpty()
    Assert.that(actionEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(actionEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(actionEvent.action.id).isNotEmpty()
    Assert.that(actionEvent.action.type).isEqualTo("custom")
    Assert.that(actionEvent.action.loading_time).isEqualTo(0)
    Assert.that(actionEvent.action.target.name).isEqualTo(fakeAction.target)
    Assert.that(actionEvent.action.error.count).isEqualTo(0)
    Assert.that(actionEvent.action.resource.count).isEqualTo(0)
    Assert.that(actionEvent.context).isEqualTo(m.fakeGlobalContext)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope and a global user info
'  When: handling an event (addAction) type=custom
'  Then: write a custom action event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAddCustomActionEventWithUserInfo_ThenWriteViewEvent() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeAction = { target: IG_GetString(16), type: "custom" }
    fakeEvent = { mock: "event", eventType: "addAction", action: fakeAction }
    m.global.setField("datadogUserInfo", m.fakeGlobalUserInfo)

    ' When
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)
    sleep(50)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    if (updates.count() = 0)
        return "Expected writeEvent to be updated"
    end if
    Assert.that(updates).hasSize(1)
    actionEvent = ParseJson(updates[0])
    Assert.that(actionEvent).isNotInvalid()
    Assert.that(actionEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(actionEvent.date).isInRange(m.startTimestamp&, m.startTimestamp& + 50)
    Assert.that(actionEvent.service).isEqualTo(fakeService)
    Assert.that(actionEvent.session.has_replay).isEqualTo(false)
    Assert.that(actionEvent.session.id).isNotEmpty()
    Assert.that(actionEvent.session.type).isEqualTo("user")
    Assert.that(actionEvent.source).isEqualTo("roku")
    Assert.that(actionEvent.type).isEqualTo("action")
    Assert.that(actionEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(actionEvent.view.id).isNotEmpty()
    Assert.that(actionEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(actionEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(actionEvent.action.id).isNotEmpty()
    Assert.that(actionEvent.action.type).isEqualTo("custom")
    Assert.that(actionEvent.action.loading_time).isEqualTo(0)
    Assert.that(actionEvent.action.target.name).isEqualTo(fakeAction.target)
    Assert.that(actionEvent.action.error.count).isEqualTo(0)
    Assert.that(actionEvent.action.resource.count).isEqualTo(0)
    Assert.that(actionEvent.usr).isEqualTo(m.fakeGlobalUserInfo)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: calling handleEvent (type=any)
'  Then: delegates the event to the child scope
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAnyEvent_ThenDelegateToActiveActionScope() as string
    ' Given
    mockScope = CreateObject("roSGNode", "MockRumScope")
    mockScope@.stubCall("isActive", {}, true)
    m.testedScope.activeAction = mockScope
    fakeEvent = { mock: "event", eventType: "any" }
    fakeWriter = { mock: "writer" }

    ' When
    m.testedScope@.handleEvent(fakeEvent, fakeWriter)

    ' Then
    Assert.that(m.testedScope.activeAction.subtype()).isEqualTo("MockRumScope")
    return mockScope@.assertFunctionCalled("handleEvent", { event: fakeEvent, writer: fakeWriter })
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: calling handleEvent (type=any)
'  Then: delegates the event to the child scope
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleAnyEventActionNotActive_ThenDiscardIt() as string
    ' Given
    mockScope = CreateObject("roSGNode", "MockRumScope")
    mockScope@.stubCall("isActive", {}, false)
    m.testedScope.activeAction = mockScope
    fakeEvent = { mock: "event", eventType: "any" }
    fakeWriter = { mock: "writer" }

    ' When
    m.testedScope@.handleEvent(fakeEvent, fakeWriter)
    datadogroku_ddLogVerbose("Back from handleEvent " + TF_Utils__AsString(m.testedScope.activeAction))
    sleep(50)

    ' Then
    Assert.that(m.testedScope.activeAction).isEqualTo(invalid)
    return mockScope@.assertFunctionCalled("handleEvent", { event: fakeEvent, writer: fakeWriter })
end function

'----------------------------------------------------------------
' Given: a RumViewScope
'  When: handling an event (keep alive)
'  Then: writes a view event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleKeepAliveEvent_ThenWriteViewUpdate() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeEvent = { mock: "event", eventType: "keepAlive" }

    ' When
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    viewEvent = ParseJson(updates[0])
    Assert.that(viewEvent).isNotInvalid()
    Assert.that(viewEvent._dd.document_version).isEqualTo(1)
    Assert.that(viewEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(viewEvent.date).isInRange(m.startTimestamp&, m.startTimestamp& + 5)
    Assert.that(viewEvent.service).isEqualTo(fakeService)
    Assert.that(viewEvent.session.has_replay).isEqualTo(false)
    Assert.that(viewEvent.session.id).isNotEmpty()
    Assert.that(viewEvent.session.type).isEqualTo("user")
    Assert.that(viewEvent.source).isEqualTo("roku")
    Assert.that(viewEvent.type).isEqualTo("view")
    Assert.that(viewEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(viewEvent.view.id).isNotEmpty()
    Assert.that(viewEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(viewEvent.view.time_spent).isInRange(1000000, 10000000)
    Assert.that(viewEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(viewEvent.view.action.count).isEqualTo(0)
    Assert.that(viewEvent.view.error.count).isEqualTo(0)
    Assert.that(viewEvent.view.resource.count).isEqualTo(0)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope and a global rum context
'  When: handling an event (keep alive)
'  Then: writes a view event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleKeepAliveEventWithContext_ThenWriteViewUpdate() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeEvent = { mock: "event", eventType: "keepAlive" }
    m.global.setField("datadogContext", m.fakeGlobalContext)

    ' When
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    viewEvent = ParseJson(updates[0])
    Assert.that(viewEvent).isNotInvalid()
    Assert.that(viewEvent._dd.document_version).isEqualTo(1)
    Assert.that(viewEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(viewEvent.date).isInRange(m.startTimestamp&, m.startTimestamp& + 5)
    Assert.that(viewEvent.service).isEqualTo(fakeService)
    Assert.that(viewEvent.session.has_replay).isEqualTo(false)
    Assert.that(viewEvent.session.id).isNotEmpty()
    Assert.that(viewEvent.session.type).isEqualTo("user")
    Assert.that(viewEvent.source).isEqualTo("roku")
    Assert.that(viewEvent.type).isEqualTo("view")
    Assert.that(viewEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(viewEvent.view.id).isNotEmpty()
    Assert.that(viewEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(viewEvent.view.time_spent).isInRange(1000000, 10000000)
    Assert.that(viewEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(viewEvent.view.action.count).isEqualTo(0)
    Assert.that(viewEvent.view.error.count).isEqualTo(0)
    Assert.that(viewEvent.view.resource.count).isEqualTo(0)
    Assert.that(viewEvent.context).isEqualTo(m.fakeGlobalContext)
    return ""
end function

'----------------------------------------------------------------
' Given: a RumViewScope and a global user info
'  When: handling an event (keep alive)
'  Then: writes a view event
'----------------------------------------------------------------
function RumViewScopeTest__WhenHandleKeepAliveEventWithUserInfo_ThenWriteViewUpdate() as string
    ' Given
    fakeApplicationId = IG_GetString(32)
    fakeApplicationVersion = IG_GetString(32)
    fakeService = IG_GetString(32)
    fakeSessionId = IG_GetString(32)
    fakeParentContext = {
        applicationId: fakeApplicationId,
        service: fakeService,
        sessionId: fakeSessionId,
        applicationVersion: fakeApplicationVersion
    }
    m.mockParentScope@.stubCall("getRumContext", {}, fakeParentContext)
    fakeEvent = { mock: "event", eventType: "keepAlive" }
    m.global.setField("datadogUserInfo", m.fakeGlobalUserInfo)

    ' When
    m.testedScope@.handleEvent(fakeEvent, m.mockWriter)

    ' Then
    updates = m.mockWriter@.getFieldUpdates("writeEvent")
    Assert.that(updates).hasSize(1)
    viewEvent = ParseJson(updates[0])
    Assert.that(viewEvent).isNotInvalid()
    Assert.that(viewEvent._dd.document_version).isEqualTo(1)
    Assert.that(viewEvent.application.id).isEqualTo(fakeApplicationId)
    Assert.that(viewEvent.date).isInRange(m.startTimestamp&, m.startTimestamp& + 5)
    Assert.that(viewEvent.service).isEqualTo(fakeService)
    Assert.that(viewEvent.session.has_replay).isEqualTo(false)
    Assert.that(viewEvent.session.id).isNotEmpty()
    Assert.that(viewEvent.session.type).isEqualTo("user")
    Assert.that(viewEvent.source).isEqualTo("roku")
    Assert.that(viewEvent.type).isEqualTo("view")
    Assert.that(viewEvent.version).isEqualTo(fakeApplicationVersion)
    Assert.that(viewEvent.view.id).isNotEmpty()
    Assert.that(viewEvent.view.name).isEqualTo(m.fakeViewName)
    Assert.that(viewEvent.view.time_spent).isInRange(1000000, 10000000)
    Assert.that(viewEvent.view.url).isEqualTo(m.fakeViewUrl)
    Assert.that(viewEvent.view.action.count).isEqualTo(0)
    Assert.that(viewEvent.view.error.count).isEqualTo(0)
    Assert.that(viewEvent.view.resource.count).isEqualTo(0)
    Assert.that(viewEvent.usr).isEqualTo(m.fakeGlobalUserInfo)
    return ""
end function
